link_home: "https://www.railstutorial.org"
link_help1: "https://www.railstutorial.org/help"
link_help2: "https://www.railstutorial.org/book"
link_about: "http://screencasts.railstutorial.org/"
link_about2: "http://rubyonrails.org/"
link_contact: "https://www.railstutorial.org/contact"
link_new: "http://news.railstutorial.org/"
link_footer: "http://www.michaelhartl.com/"
email: "from@example.com"
en: "en"
vi: "vi"
users:
  your_email:
    maximum: 255
  your_name:
    maximum: 50
  password:
    minimum: 6
valid_email_regex: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
